version: '3'
services:
  # Serviço do banco de dados MySQL
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ehr
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Serviço do back-end (Node.js)
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: ehr

  # Serviço do front-end (React)
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    depends_on:
      - backend

volumes:
  db_data:
